name: 'Enhanced ENV Azure key vault - Get Secrets'
description: 'Get Secrets from Azure Key Vault instance and set as ENV variables.'
inputs:
  KEY_VAULT_URI:
    description: 'Nombre o la url del keyvault'
    required: true
  SHOW_ENV_VARIABLES:
    description: 'Mostrar los secretos junto con loas variables de entorno o solo los secretos'
    required: true
outputs:
  env:
    description: 'The environment parameters'
branding:
  icon: 'download-cloud'
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/index.js'