name: 'Enhanced ENV Azure key vault - Get Secrets'
description: 'Get Secrets from Azure Key Vault instance and set as ENV variables.'
inputs:
  KEY_VAULT_URI:
    description: 'Name of the azure key vault'
    required: true
outputs:
  env:
    description: 'The environment parameters'
branding:
  icon: 'download-cloud'
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/index.js'