name: 'Azure KV Secrets Loader'
description: 'Lee los secretos de un keyvault y los añade a las variables de entorno, ademas indica si el secreto esta caducado'
inputs:
  KEY_VAULT_URI:
    description: 'Nombre o la url del keyvault'
    required: true
  SHOW_ENV_VARIABLES:
    description: 'true | false, Mostrar los secretos junto con loas variables de entorno o solo los secretos'
    required: true
outputs:
  env:
    description: 'The environment parameters'
branding:
  icon: 'download-cloud'
  color: 'blue'
runs:
  using: 'node16'
  main: 'lib/index.js'