name: prueba

on: 
  workflow_dispatch:
    

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Get the secrets
        uses: AsierSalguero/KVLoader@v4
        with:
          KEY_VAULT_URI: ${{ secrets.KEY_VAULT_URI }}
        id: aenv
