name: prueba

on: 
  workflow_dispatch:
    

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Get the secrets
        uses: AsierSalguero/KVLoader@v8
        with:
          KEY_VAULT_URI: "https://developeraaaaaaaaaaaaa.vault.azure.net/"
        id: aenv
