name: prueba

on: 
  workflow_dispatch:
    

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
              
      - name: Get the secrets
        uses: AsierSalguero/KVLoader@v1
        with:
          KEY_VAULT_URI: "https://developeraaaaaaaaaaaaa.vault.azure.net/"
        id: aenv
